# Generated by Django 5.2.17 on 2026-08-09 22:17

import apps.accounts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('label', models.CharField(blank=True, max_length=60, verbose_name='label')),
                ('recipient_name', models.CharField(max_length=160, verbose_name='recipient')),
                ('postal_code', models.CharField(max_length=16, verbose_name='postal code')),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('number', models.CharField(max_length=32, verbose_name='number')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='complement')),
                ('neighborhood', models.CharField(max_length=120, verbose_name='neighborhood')),
                ('city', models.CharField(max_length=120, verbose_name='city')),
                ('state', models.CharField(max_length=64, verbose_name='state')),
                ('country', models.CharField(default='BR', max_length=2, verbose_name='country')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='reference point')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_default', models.BooleanField(default=False, verbose_name='default address')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('purpose', models.CharField(choices=[('EMAIL_VERIFICATION', 'Email verification'), ('PASSWORD_RESET', 'Password reset')], max_length=32, verbose_name='purpose')),
                ('token_hash', models.CharField(db_index=True, max_length=64, verbose_name='token hash')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='requested from')),
            ],
            options={
                'verbose_name': 'authentication token',
                'verbose_name_plural': 'authentication tokens',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('successful', models.BooleanField(default=False, verbose_name='successful')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('failure_reason', models.CharField(blank=True, max_length=64, verbose_name='failure reason')),
            ],
            options={
                'verbose_name': 'login attempt',
                'verbose_name_plural': 'login attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='code')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(max_length=64, verbose_name='slug')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('is_system', models.BooleanField(default=False, help_text='System roles are re-synced on deploy and cannot be deleted.', verbose_name='system role')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'user role',
                'verbose_name_plural': 'user roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('user_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('ADMINISTRATOR', 'Administrator'), ('PLATFORM_ADMIN', 'Platform administrator')], default='CUSTOMER', max_length=20, verbose_name='type')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to the emergency Django admin, not the merchant dashboard.', verbose_name='django admin access')),
                ('is_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('accepted_terms_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted terms at')),
                ('marketing_opt_in', models.BooleanField(default=False, verbose_name='accepts marketing')),
                ('anonymized_at', models.DateTimeField(blank=True, null=True, verbose_name='anonymised at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
