# Generated by Django 5.2.17 on 2026-09-13 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpermission_user_direct_permissions_and_more'),
        ('media', '0004_alter_mediaasset_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatars', to='media.mediaasset', verbose_name='profile picture'),
        ),
    ]
