# Generated by Django 5.2.17 on 2026-08-10 02:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('provider', models.CharField(max_length=32, verbose_name='provider')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text="The provider's identifier, used for reconciliation.", max_length=128, verbose_name='provider reference')),
                ('method', models.CharField(choices=[('PIX', 'PIX'), ('CREDIT_CARD', 'Credit card'), ('DEBIT_CARD', 'Debit card'), ('CASH', 'Cash on delivery'), ('WALLET', 'Digital wallet')], default='PIX', max_length=16, verbose_name='method')),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting payment'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially refunded')], default='PENDING', max_length=20, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='refunded')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Charged by the PSP. Subtracted from revenue in financial reports.', max_digits=12, verbose_name='provider fee')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='currency')),
                ('pix_payload', models.TextField(blank=True, help_text='The BR Code string the customer pastes into their bank app.', verbose_name='PIX copy-and-paste code')),
                ('pix_qr_code', models.TextField(blank=True, help_text='Base64 PNG rendering of the BR Code.', verbose_name='PIX QR code')),
                ('pix_transaction_id', models.CharField(blank=True, max_length=64, verbose_name='PIX txid')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expires at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='failure reason')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='provider metadata')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('provider', models.CharField(max_length=32, verbose_name='provider')),
                ('provider_event_id', models.CharField(db_index=True, max_length=128, verbose_name='event id')),
                ('event_type', models.CharField(max_length=64, verbose_name='event type')),
                ('payload_hash', models.CharField(help_text='SHA-256 of the raw body — enough to detect duplicates and tampering.', max_length=64, verbose_name='payload hash')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='signature valid')),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('IGNORED', 'Ignored'), ('FAILED', 'Failed')], default='RECEIVED', max_length=12, verbose_name='processing status')),
                ('processing_error', models.CharField(blank=True, max_length=255, verbose_name='processing error')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.payment', verbose_name='payment')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'payment event',
                'verbose_name_plural': 'payment events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=12, verbose_name='status')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='provider reference')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='payment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'refund',
                'verbose_name_plural': 'refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='payments_pa_tenant__01c4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', '-created_at'], name='payments_pa_order_i_288dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'expires_at'], name='payments_pa_status_04c3f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__lte', models.F('amount'))), name='payment_refund_within_amount'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('provider', 'external_id'), name='uniq_payment_provider_external_id'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['payment', '-created_at'], name='payments_pa_payment_a3a0f0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['processing_status', '-created_at'], name='payments_pa_process_1b07d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id', ''), _negated=True), fields=('provider', 'provider_event_id'), name='uniq_payment_event_provider_id'),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'),
        ),
    ]
