# Generated by Django 5.2.17 on 2026-08-09 22:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='subtitle')),
                ('link_type', models.CharField(choices=[('NONE', 'No link'), ('CATEGORY', 'Category'), ('PRODUCT', 'Product'), ('PROMOTION', 'Promotion'), ('COLLECTION', 'Collection'), ('SEARCH', 'Search term'), ('EXTERNAL', 'External URL')], default='NONE', max_length=16, verbose_name='link type')),
                ('link_target', models.CharField(blank=True, max_length=512, verbose_name='link target')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='starts at')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='ends at')),
                ('priority', models.IntegerField(default=0, help_text='Higher values are shown first.', verbose_name='priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('impression_count', models.PositiveIntegerField(default=0, verbose_name='impressions')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='clicks')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('REPORT', 'Report'), ('CONTRACT', 'Contract'), ('PRODUCT_SHEET', 'Product sheet'), ('OTHER', 'Other')], default='OTHER', max_length=24, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('related_type', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='related type')),
                ('related_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='related id')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document')], default='IMAGE', max_length=16, verbose_name='kind')),
                ('folder', models.CharField(choices=[('products', 'Product images'), ('banners', 'Banners'), ('branding', 'Branding'), ('categories', 'Category images'), ('documents', 'Documents'), ('reports', 'Generated reports')], default='products', max_length=32, verbose_name='folder')),
                ('status', models.CharField(choices=[('PENDING', 'Pending processing'), ('READY', 'Ready'), ('FAILED', 'Processing failed')], default='PENDING', max_length=16, verbose_name='status')),
                ('storage_key', models.CharField(max_length=512, unique=True, verbose_name='storage key')),
                ('bucket', models.CharField(blank=True, max_length=128, verbose_name='bucket')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('content_type', models.CharField(max_length=128, verbose_name='MIME type')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='size in bytes')),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('alt_text', models.CharField(blank=True, help_text='Required for accessibility on anything user-visible.', max_length=255, verbose_name='alt text')),
                ('derivatives', models.JSONField(blank=True, default=dict, verbose_name='derivatives')),
                ('is_public', models.BooleanField(default=True, help_text='Product images are public; documents are not.', verbose_name='public')),
            ],
            options={
                'verbose_name': 'media asset',
                'verbose_name_plural': 'media assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
