# Generated by Django 5.2.17 on 2026-08-09 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='media.mediaasset', verbose_name='file'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banners', to='media.mediaasset', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_banners', to='media.mediaasset', verbose_name='mobile image'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['tenant', 'folder', '-created_at'], name='media_media_tenant__c19f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['tenant', 'checksum'], name='media_media_tenant__f85ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'document_type', '-created_at'], name='media_docum_tenant__2b4f57_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['related_type', 'related_id'], name='media_docum_related_aea540_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['tenant', 'is_active', '-priority'], name='media_banne_tenant__41e36c_idx'),
        ),
    ]
