# Generated by Django 5.2.17 on 2026-08-11 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cta_label',
            field=models.CharField(blank=True, help_text='Leave empty to show the banner without a button.', max_length=40, verbose_name='button label'),
        ),
        migrations.AddField(
            model_name='banner',
            name='overlay_opacity',
            field=models.PositiveSmallIntegerField(default=45, help_text='Percentage of dark scrim over the image. The merchant controls it because how much a photo needs depends entirely on the photo.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='overlay strength'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_align',
            field=models.CharField(choices=[('LEFT', 'Left'), ('CENTER', 'Centre'), ('RIGHT', 'Right')], default='CENTER', max_length=8, verbose_name='text alignment'),
        ),
    ]
