# Generated by Django 5.2.17 on 2026-09-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_banner_cta_label_banner_overlay_opacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='folder',
            field=models.CharField(choices=[('products', 'Product images'), ('banners', 'Banners'), ('branding', 'Branding'), ('categories', 'Category images'), ('documents', 'Documents'), ('reports', 'Generated reports'), ('avatars', 'Profile pictures')], default='products', max_length=32, verbose_name='folder'),
        ),
    ]
