# Generated by Django 5.2.17 on 2026-09-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_mediaasset_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='placeholder',
            field=models.TextField(blank=True, help_text='A tiny blurred copy as a data URI, shown while the real image decodes. Stored on the row rather than as a file so it arrives with the JSON and costs no extra request.', verbose_name='placeholder'),
        ),
    ]
