# Generated by Django 5.2.17 on 2026-08-09 22:17

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('account_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank account'), ('CARD', 'Card acquirer'), ('OTHER', 'Other')], default='BANK', max_length=12, verbose_name='type')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='opening balance')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'financial account',
                'verbose_name_plural': 'financial accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.SlugField(max_length=48, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('kind', models.CharField(choices=[('SALES', 'Sales revenue'), ('OTHER_REVENUE', 'Other revenue'), ('COGS', 'Cost of goods sold'), ('OPERATING_EXPENSE', 'Operating expense'), ('PAYMENT_FEE', 'Payment fees'), ('DELIVERY_COST', 'Delivery costs'), ('TAX', 'Taxes')], max_length=20, verbose_name='kind')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'financial category',
                'verbose_name_plural': 'financial categories',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('transaction_type', models.CharField(choices=[('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=10, verbose_name='type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled')], default='SETTLED', max_length=10, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('occurred_on', models.DateField(db_index=True, help_text="Business date in the tenant's timezone, not the server's.", verbose_name='date')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('reference_type', models.CharField(blank=True, max_length=32, verbose_name='reference type')),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='reference id')),
            ],
            options={
                'verbose_name': 'financial transaction',
                'verbose_name_plural': 'financial transactions',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
    ]
