# Generated by Django 5.2.17 on 2026-08-09 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='financialcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.financialcategory'),
        ),
        migrations.AddField(
            model_name='financialcategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.financialaccount', verbose_name='account'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.financialcategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='uniq_default_financial_account'),
        ),
        migrations.AddConstraint(
            model_name='financialcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_financial_category_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['tenant', 'occurred_on'], name='finance_fin_tenant__13ef3c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['tenant', 'transaction_type', 'occurred_on'], name='finance_fin_tenant__ded3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='finance_fin_referen_e6588b_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='financial_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='financialtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_id', ''), _negated=True), fields=('tenant', 'reference_type', 'reference_id', 'category'), name='uniq_financial_entry_per_reference_category'),
        ),
    ]
