# Generated by Django 5.2.17 on 2026-09-14 21:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('tenants', '0009_backfill_back_soon_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='name')),
                ('year', models.PositiveSmallIntegerField(verbose_name='year')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'budget',
                'verbose_name_plural': 'budgets',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('planned_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='planned amount')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.budget', verbose_name='budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.financialcategory', verbose_name='category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'budget line',
                'verbose_name_plural': 'budget lines',
                'ordering': ['category__kind', 'category__name'],
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['tenant', '-year', '-month'], name='finance_bud_tenant__146b63_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('tenant', 'year', 'month'), name='uniq_budget_per_tenant_month'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('budget', 'category'), name='uniq_budget_line_per_category'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('planned_amount__gte', 0)), name='budget_line_amount_non_negative'),
        ),
    ]
