# Generated by Django 5.2.17 on 2026-08-09 22:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase received'), ('SALE', 'Sale'), ('RESERVATION', 'Reserved'), ('RELEASE', 'Reservation released'), ('ADJUSTMENT', 'Manual adjustment'), ('CANCELLATION', 'Order cancelled'), ('RETURN', 'Customer return'), ('LOSS', 'Loss or breakage'), ('EXPIRATION', 'Expired'), ('INITIAL', 'Opening balance')], max_length=16, verbose_name='type')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantity')),
                ('balance_after', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='balance after')),
                ('reference_type', models.CharField(blank=True, max_length=32, verbose_name='reference type')),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='reference id')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
            ],
            options={
                'verbose_name': 'stock movement',
                'verbose_name_plural': 'stock movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantity')),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('COMMITTED', 'Committed'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired')], default='HELD', max_length=12, verbose_name='status')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
            ],
            options={
                'verbose_name': 'stock reservation',
                'verbose_name_plural': 'stock reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='physical quantity')),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='reserved quantity')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='minimum stock')),
                ('reorder_threshold', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='reorder threshold')),
                ('track_stock', models.BooleanField(default=True, help_text='Turn off for made-to-order items such as fresh bakery batches.', verbose_name='track stock')),
                ('location', models.CharField(blank=True, max_length=64, verbose_name='location')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'inventory item',
                'verbose_name_plural': 'inventory items',
            },
        ),
    ]
