# Generated by Django 5.2.17 on 2026-09-02 02:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_pg_trgm_extension'),
        ('inventory', '0002_initial'),
        ('tenants', '0003_refresh_default_brand_colours'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(blank=True, help_text="The supplier's lot number, where there is one.", max_length=64, verbose_name='batch code')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='quantity remaining')),
                ('expiry_date', models.DateField(db_index=True, verbose_name='expiry date')),
                ('received_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='received on')),
                ('supplier', models.CharField(blank=True, max_length=120, verbose_name='supplier')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='What this lot cost per unit, for margin and write-off value.', max_digits=12, null=True, verbose_name='cost price')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='catalog.product', verbose_name='product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'stock batch',
                'verbose_name_plural': 'stock batches',
                'ordering': ['expiry_date', 'received_date'],
                'indexes': [models.Index(fields=['tenant', 'expiry_date'], name='inventory_s_tenant__d5c4ee_idx'), models.Index(fields=['tenant', 'product', 'expiry_date'], name='inventory_s_tenant__dcef2a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='batch_quantity_non_negative')],
            },
        ),
    ]
