# Generated by Django 5.2.17 on 2026-09-13 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_pg_trgm_extension'),
        ('inventory', '0003_stockbatch'),
        ('tenants', '0008_tenantsettings_hide_out_of_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(blank=True, help_text='Used when the request came from a visitor with no account.', max_length=254, verbose_name='email')),
                ('locale', models.CharField(blank=True, help_text='Language the request was made in, so the email matches it.', max_length=10, verbose_name='locale')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='notified at')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restock_alerts', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_alerts', to='catalog.product', verbose_name='product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'restock alert',
                'verbose_name_plural': 'restock alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'product', 'notified_at'], name='inventory_r_tenant__7b722c_idx'), models.Index(fields=['tenant', '-created_at'], name='inventory_r_tenant__e79358_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('customer__isnull', False), models.Q(('email', ''), _negated=True), _connector='OR'), name='restock_alert_has_a_recipient'), models.UniqueConstraint(condition=models.Q(('customer__isnull', False)), fields=('tenant', 'product', 'customer'), name='uniq_restock_alert_per_customer'), models.UniqueConstraint(condition=models.Q(('customer__isnull', True)), fields=('tenant', 'product', 'email'), name='uniq_restock_alert_per_email')],
            },
        ),
    ]
