# Generated by Django 5.2.17 on 2026-08-09 22:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('actor_label', models.CharField(blank=True, help_text='Kept so the trail stays readable after an account is anonymised.', max_length=255, verbose_name='actor label')),
                ('action', models.CharField(db_index=True, max_length=64, verbose_name='action')),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='resource type')),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='resource id')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='previous values')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='new values')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='request id')),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system-initiated actions such as webhooks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
