# Generated by Django 5.2.17 on 2026-08-09 22:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('report_type', models.CharField(choices=[('SALES', 'Sales report'), ('PRODUCTS', 'Product performance'), ('CUSTOMERS', 'Customer report'), ('INVENTORY', 'Inventory report'), ('FINANCIAL', 'Financial statement'), ('ORDER_RECEIPT', 'Order receipt')], max_length=20, verbose_name='type')),
                ('output_format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV')], default='PDF', max_length=6, verbose_name='format')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=10, verbose_name='status')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Period and filters the report was generated with.', verbose_name='parameters')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='error')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_jobs', to='media.mediaasset', verbose_name='generated file')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'report job',
                'verbose_name_plural': 'report jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='reports_rep_tenant__605820_idx')],
            },
        ),
    ]
