# Generated by Django 5.2.17 on 2026-08-09 22:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(help_text='Used for subdomain and API routing.', unique=True, validators=[django.core.validators.RegexValidator(message='Use lowercase letters, numbers and hyphens.', regex='^[a-z0-9](?:[a-z0-9-]{1,48}[a-z0-9])$')], verbose_name='slug')),
                ('legal_name', models.CharField(max_length=255, verbose_name='legal name')),
                ('trade_name', models.CharField(max_length=255, verbose_name='trade name')),
                ('tax_id', models.CharField(blank=True, help_text='CNPJ in Brazil. Stored as typed; formatting is a display concern.', max_length=32, verbose_name='tax id')),
                ('support_email', models.EmailField(max_length=254, verbose_name='support email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('whatsapp', models.CharField(blank=True, max_length=32, verbose_name='whatsapp')),
                ('postal_code', models.CharField(blank=True, max_length=16, verbose_name='postal code')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='street')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='complement')),
                ('neighborhood', models.CharField(blank=True, max_length=120, verbose_name='neighborhood')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=64, verbose_name='state')),
                ('country', models.CharField(default='BR', max_length=2, verbose_name='country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('timezone', models.CharField(default='America/Sao_Paulo', help_text='Determines the business day used by every report.', max_length=64, verbose_name='timezone')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='currency')),
                ('locale', models.CharField(default='pt-BR', max_length=10, verbose_name='locale')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('custom_domain', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='custom domain')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ['trade_name'],
                'indexes': [models.Index(fields=['is_active', 'slug'], name='tenants_ten_is_acti_c80453_idx'), models.Index(fields=['status'], name='tenants_ten_status_e7eaee_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('primary_color', models.CharField(default='#7B2D3B', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hexadecimal colour, for example #7B2D3B.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='primary colour')),
                ('secondary_color', models.CharField(default='#2E2A2B', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hexadecimal colour, for example #7B2D3B.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='secondary colour')),
                ('accent_color', models.CharField(default='#A64253', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hexadecimal colour, for example #7B2D3B.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='accent colour')),
                ('dark_primary_color', models.CharField(default='#E8C9CF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hexadecimal colour, for example #7B2D3B.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='primary colour (dark)')),
                ('tagline', models.CharField(blank=True, max_length=160, verbose_name='tagline')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('website_url', models.URLField(blank=True, verbose_name='website')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branding_favicons', to='media.mediaasset', verbose_name='favicon')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branding_logos', to='media.mediaasset', verbose_name='logo')),
                ('logo_dark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branding_dark_logos', to='media.mediaasset', verbose_name='logo (dark theme)')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'tenant branding',
                'verbose_name_plural': 'tenant branding',
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order_number_prefix', models.CharField(default='MF', max_length=8, verbose_name='order number prefix')),
                ('allow_orders_when_closed', models.BooleanField(default=True, help_text='Scheduled orders placed outside business hours.', verbose_name='accept orders while closed')),
                ('auto_confirm_paid_orders', models.BooleanField(default=True, verbose_name='auto-confirm paid orders')),
                ('max_items_per_order', models.PositiveIntegerField(default=200, verbose_name='max items per order')),
                ('prices_include_tax', models.BooleanField(default=True, help_text='Brazilian retail displays tax-inclusive prices.', verbose_name='prices include tax')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='default tax rate (%)')),
                ('allow_backorder', models.BooleanField(default=False, help_text='When off, stock can never go negative (invariant #6).', verbose_name='allow selling without stock')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='low stock threshold')),
                ('notify_on_new_order', models.BooleanField(default=True, verbose_name='notify staff about new orders')),
                ('email_sender_name', models.CharField(blank=True, max_length=120, verbose_name='email sender name')),
                ('email_reply_to', models.EmailField(blank=True, max_length=254, verbose_name='reply-to')),
                ('privacy_policy_url', models.URLField(blank=True, verbose_name='privacy policy URL')),
                ('terms_url', models.URLField(blank=True, verbose_name='terms of use URL')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'tenant settings',
                'verbose_name_plural': 'tenant settings',
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='weekday')),
                ('opens_at', models.TimeField(verbose_name='opens at')),
                ('closes_at', models.TimeField(verbose_name='closes at')),
                ('is_closed', models.BooleanField(default=False, verbose_name='closed all day')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'business hours',
                'verbose_name_plural': 'business hours',
                'ordering': ['weekday', 'opens_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'weekday', 'opens_at'), name='uniq_business_hours_tenant_weekday_open'), models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at')), ('is_closed', True), _connector='OR'), name='business_hours_close_after_open')],
            },
        ),
    ]
