# Generated by Django 5.2.17 on 2026-08-11 02:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbranding',
            name='accent_color',
            field=models.CharField(default='#B02233', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hexadecimal colour, for example #7B2D3B.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='accent colour'),
        ),
        migrations.AlterField(
            model_name='tenantbranding',
            name='dark_primary_color',
            field=models.CharField(default='#E2495D', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hexadecimal colour, for example #7B2D3B.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='primary colour (dark)'),
        ),
        migrations.AlterField(
            model_name='tenantbranding',
            name='primary_color',
            field=models.CharField(default='#8C1425', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hexadecimal colour, for example #7B2D3B.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='primary colour'),
        ),
        migrations.AlterField(
            model_name='tenantbranding',
            name='secondary_color',
            field=models.CharField(default='#211E1F', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hexadecimal colour, for example #7B2D3B.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='secondary colour'),
        ),
    ]
