# Generated by Django 5.2.17 on 2026-09-03 01:50

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_refresh_default_brand_colours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='floating_tools',
            field=models.JSONField(default=apps.tenants.models.default_floating_tools, help_text='Which shortcuts the floating button offers, and in what order.', verbose_name='floating tools'),
        ),
    ]
