# Generated by Django 5.2.17 on 2026-09-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsettings_floating_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='smtp_from_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='from address'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255, verbose_name='SMTP host'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='SMTP password'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='SMTP port'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='use TLS'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='SMTP username'),
        ),
    ]
