# Generated by Django 5.2.17 on 2026-09-03 12:52

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenantsettings_smtp_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='home_layout',
            field=models.JSONField(blank=True, default=apps.tenants.models.default_home_layout, verbose_name='home layout'),
        ),
    ]
