# Generated by Django 5.2.17 on 2026-09-13 15:39

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenantsettings_home_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='hero',
            field=models.JSONField(blank=True, default=apps.tenants.models.default_hero, verbose_name='hero'),
        ),
    ]
