# Generated by Django 5.2.17 on 2026-09-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenantsettings_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='hide_out_of_stock',
            field=models.BooleanField(default=False, help_text='Off by default. An empty shelf a shopper can ask to be told about is a sale delayed; one they never see is a sale lost, and the shop learns nothing about the demand it missed.', verbose_name='hide products that are out of stock'),
        ),
    ]
