# Generated by Django 5.2.17 on 2026-09-15 00:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_backfill_back_soon_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(max_length=140, verbose_name='slug')),
                ('icon', models.CharField(blank=True, default='mdi-help-circle-outline', help_text='Material Design Icons name, e.g. mdi-truck-outline.', max_length=64, verbose_name='icon')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'FAQ category',
                'verbose_name_plural': 'FAQ categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FaqEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10, verbose_name='status')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tenants.faqcategory', verbose_name='category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FAQ entry',
                'verbose_name_plural': 'FAQ entries',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='faqcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_faq_category_slug'),
        ),
        migrations.AddIndex(
            model_name='faqentry',
            index=models.Index(fields=['tenant', 'status', 'position'], name='tenants_faq_tenant__6fb41c_idx'),
        ),
    ]
