# Generated by Django 5.2.17 on 2026-08-09 22:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('number', models.CharField(db_index=True, max_length=32, verbose_name='order number')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='customer name')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='customer email')),
                ('customer_phone', models.CharField(blank=True, max_length=32, verbose_name='customer phone')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Awaiting payment'), ('PAYMENT_PROCESSING', 'Processing payment'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Being prepared'), ('READY_FOR_PICKUP', 'Ready for pickup'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PAYMENT_FAILED', 'Payment failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially refunded')], default='DRAFT', max_length=24, verbose_name='status')),
                ('delivery_method', models.CharField(default='PICKUP', max_length=16, verbose_name='delivery method')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='currency')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='subtotal')),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='discount')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='delivery fee')),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='tax')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total')),
                ('refunded_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='refunded')),
                ('coupon_code', models.CharField(blank=True, max_length=32, verbose_name='coupon')),
                ('customer_note', models.CharField(blank=True, max_length=500, verbose_name='customer note')),
                ('internal_note', models.TextField(blank=True, verbose_name='internal note')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='scheduled for')),
                ('estimated_ready_at', models.DateTimeField(blank=True, null=True, verbose_name='estimated ready at')),
                ('placed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='placed at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='cancellation reason')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('recipient_name', models.CharField(max_length=160, verbose_name='recipient')),
                ('postal_code', models.CharField(max_length=16, verbose_name='postal code')),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('number', models.CharField(max_length=32, verbose_name='number')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='complement')),
                ('neighborhood', models.CharField(max_length=120, verbose_name='neighborhood')),
                ('city', models.CharField(max_length=120, verbose_name='city')),
                ('state', models.CharField(max_length=64, verbose_name='state')),
                ('country', models.CharField(default='BR', max_length=2, verbose_name='country')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='reference point')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='orders.order', verbose_name='order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'order address',
                'verbose_name_plural': 'order addresses',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('product_name', models.CharField(max_length=255, verbose_name='product')),
                ('product_sku', models.CharField(blank=True, max_length=64, verbose_name='SKU')),
                ('unit_code', models.CharField(blank=True, max_length=12, verbose_name='unit')),
                ('category_name', models.CharField(blank=True, max_length=120, verbose_name='category')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='unit price')),
                ('base_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='list price')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Captured for margin reporting. Never shown to customers.', max_digits=12, null=True, verbose_name='unit cost')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='discount')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='line total')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('body', models.TextField(verbose_name='note')),
                ('is_customer_visible', models.BooleanField(default=False, verbose_name='visible to the customer')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'order note',
                'verbose_name_plural': 'order notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('old_status', models.CharField(blank=True, max_length=24, verbose_name='previous status')),
                ('new_status', models.CharField(max_length=24, verbose_name='new status')),
                ('actor_label', models.CharField(blank=True, max_length=255, verbose_name='actor')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('is_customer_visible', models.BooleanField(default=True, verbose_name='visible to the customer')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'order status history',
                'verbose_name_plural': 'order status history',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='orders_orde_tenant__1d191c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', '-created_at'], name='orders_orde_tenant__b7367d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'customer', '-created_at'], name='orders_orde_tenant__5e55b8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', '-placed_at'], name='orders_orde_tenant__5e6619_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_order_tenant_number'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='order_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_total__lte', models.F('total'))), name='order_refund_within_total'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['tenant', 'product'], name='orders_orde_tenant__93c3cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='order_item_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_1de1d7_idx'),
        ),
    ]
