# Generated by Django 5.2.17 on 2026-08-11 01:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('catalog', '0003_pg_trgm_extension'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'shopping list',
                'verbose_name_plural': 'shopping lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='quantity')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_items', to='catalog.product')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.shoppinglist', verbose_name='list')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'shopping list item',
                'verbose_name_plural': 'shopping list items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('tenant', 'customer', 'name'), name='uniq_shopping_list_name'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglistitem',
            constraint=models.UniqueConstraint(fields=('shopping_list', 'product'), name='uniq_shopping_list_item_product'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglistitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='shopping_list_item_quantity_positive'),
        ),
    ]
