# Generated by Django 5.2.17 on 2026-08-09 22:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('code', models.SlugField(max_length=64, verbose_name='code')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'price list',
                'verbose_name_plural': 'price lists',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='base price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='When set and within the schedule, this is what the customer pays.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='promotional price')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Used for margin analysis. Never shown to customers.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='cost')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='minimum quantity')),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='valid from')),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='valid until')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.pricelist', verbose_name='price list')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.product', verbose_name='product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'product price',
                'verbose_name_plural': 'product prices',
                'ordering': ['-min_quantity', '-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('field', models.CharField(default='base_price', max_length=32, verbose_name='field')),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='previous value')),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='new value')),
                ('reason', models.CharField(choices=[('INITIAL', 'Initial price'), ('MANUAL', 'Manual change'), ('PROMOTION', 'Promotion'), ('COST_CHANGE', 'Cost change'), ('SCHEDULED', 'Scheduled change'), ('IMPORT', 'Bulk import')], default='MANUAL', max_length=20, verbose_name='reason')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.product', verbose_name='product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='pricing.productprice', verbose_name='price row')),
            ],
            options={
                'verbose_name': 'price history',
                'verbose_name_plural': 'price history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_price_list_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='uniq_default_price_list_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['tenant', 'product', 'is_active'], name='pricing_pro_tenant__7eb8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', 'min_quantity', 'is_active'], name='pricing_pro_product_2a7e30_idx'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='price_base_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__gte', 0), _connector='OR'), name='price_sale_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='price_window_ordered'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['tenant', 'product', '-created_at'], name='pricing_pri_tenant__c8b343_idx'),
        ),
    ]
