# Generated by Django 5.2.17 on 2026-08-09 22:17

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('delivery_enabled', models.BooleanField(default=True, verbose_name='delivery enabled')),
                ('pickup_enabled', models.BooleanField(default=True, verbose_name='pickup enabled')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='minimum order')),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='delivery fee')),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Orders at or above this subtotal ship free. Blank disables the rule.', max_digits=12, null=True, verbose_name='free delivery from')),
                ('service_radius_km', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6, verbose_name='service radius (km)')),
                ('estimated_delivery_minutes', models.PositiveIntegerField(default=60, verbose_name='estimated delivery time (min)')),
                ('estimated_pickup_minutes', models.PositiveIntegerField(default=30, verbose_name='estimated preparation time (min)')),
                ('delivery_cutoff_minutes', models.PositiveIntegerField(default=30, help_text='Orders are refused this long before the store closes.', verbose_name='cutoff before closing (min)')),
            ],
            options={
                'verbose_name': 'delivery settings',
                'verbose_name_plural': 'delivery settings',
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('postal_code_start', models.CharField(max_length=8, verbose_name='CEP from')),
                ('postal_code_end', models.CharField(max_length=8, verbose_name='CEP to')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='fee')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='minimum order')),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='free delivery from')),
                ('estimated_minutes', models.PositiveIntegerField(default=60, verbose_name='estimated time (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'delivery zone',
                'verbose_name_plural': 'delivery zones',
                'ordering': ['postal_code_start'],
            },
        ),
    ]
