# Generated by Django 5.2.17 on 2026-08-09 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysettings',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_settings', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['tenant', 'is_active'], name='delivery_de_tenant__ebba69_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryzone',
            constraint=models.UniqueConstraint(fields=('tenant', 'postal_code_start', 'postal_code_end'), name='uniq_zone_tenant_range'),
        ),
    ]
