# Generated by Django 5.2.17 on 2026-08-09 22:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('orders', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=160, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage off'), ('FIXED', 'Fixed amount off'), ('FREE_DELIVERY', 'Free delivery'), ('BUY_X_GET_Y', 'Buy X get Y')], max_length=16, verbose_name='discount type')),
                ('scope', models.CharField(choices=[('ORDER', 'Whole order'), ('PRODUCT', 'Selected products'), ('CATEGORY', 'Selected categories')], default='ORDER', max_length=16, verbose_name='scope')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage (0–100) or a currency amount, depending on the type.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='value')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Caps a percentage discount, e.g. 20% off up to R$30.', max_digits=12, null=True, verbose_name='discount ceiling')),
                ('buy_quantity', models.PositiveSmallIntegerField(default=0, verbose_name='buy quantity')),
                ('get_quantity', models.PositiveSmallIntegerField(default=0, verbose_name='free quantity')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='minimum order')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ends at')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Blank means unlimited.', null=True, verbose_name='total usage limit')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='times used')),
                ('per_customer_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='per-customer limit')),
                ('requires_coupon', models.BooleanField(default=False, help_text='When off, the promotion applies automatically.', verbose_name='requires a coupon code')),
                ('is_stackable', models.BooleanField(default=False, help_text='Whether it can combine with other promotions.', verbose_name='stackable')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority is evaluated first.', verbose_name='priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.category', verbose_name='categories')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='catalog.product', verbose_name='products')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=32, verbose_name='code')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='maximum uses')),
                ('max_uses_per_customer', models.PositiveIntegerField(default=1, verbose_name='maximum uses per customer')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='times used')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ends at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='promotions.promotion', verbose_name='promotion')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='discount')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='promotions.coupon', verbose_name='coupon')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'coupon redemption',
                'verbose_name_plural': 'coupon redemptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coupon', 'customer'], name='promotions__coupon__52e524_idx')],
                'constraints': [models.UniqueConstraint(fields=('coupon', 'order'), name='uniq_redemption_coupon_order')],
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['tenant', 'is_active', '-priority'], name='promotions__tenant__e1c178_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='promotion_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='promotion_window_ordered'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['tenant', 'code', 'is_active'], name='promotions__tenant__57cf2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_coupon_tenant_code'),
        ),
    ]
