# Generated by Django 5.2.17 on 2026-08-09 22:17

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(max_length=140, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(max_length=140, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('position', models.IntegerField(default=0, verbose_name='position')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('locale', models.CharField(max_length=10, verbose_name='locale')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category translation',
                'verbose_name_plural': 'category translations',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'favourite',
                'verbose_name_plural': 'favourites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sku', models.CharField(max_length=64, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=280, verbose_name='slug')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='short description')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('product_type', models.CharField(choices=[('SIMPLE', 'Sold by unit'), ('WEIGHTED', 'Sold by weight'), ('BUNDLE', 'Bundle')], default='SIMPLE', max_length=16, verbose_name='type')),
                ('unit_quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Content per sold item, e.g. 1.000 for a 1 kg pack.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='package size')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('OUT_OF_STOCK', 'Out of stock'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('requires_weighing', models.BooleanField(default=False, help_text='Final price depends on the weight measured when preparing the order.', verbose_name='weighed at pickup')),
                ('requires_age_check', models.BooleanField(default=False, verbose_name='age restricted')),
                ('tax_category', models.CharField(blank=True, max_length=32, verbose_name='tax category')),
                ('max_quantity_per_order', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='max quantity per order')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='units sold')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='views')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(db_index=True, max_length=64, verbose_name='code')),
                ('barcode_type', models.CharField(choices=[('EAN13', 'EAN-13'), ('EAN8', 'EAN-8'), ('UPC', 'UPC'), ('INTERNAL', 'Internal')], default='EAN13', max_length=12, verbose_name='type')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary')),
            ],
            options={
                'verbose_name': 'barcode',
                'verbose_name_plural': 'barcodes',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('slug', models.SlugField(max_length=80, verbose_name='slug')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='colour')),
            ],
            options={
                'verbose_name': 'product tag',
                'verbose_name_plural': 'product tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('locale', models.CharField(max_length=10, verbose_name='locale')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='short description')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'product translation',
                'verbose_name_plural': 'product translations',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=12, verbose_name='code')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('kind', models.CharField(choices=[('UNIT', 'Unit'), ('WEIGHT', 'Weight'), ('VOLUME', 'Volume'), ('LENGTH', 'Length')], default='UNIT', max_length=12, verbose_name='kind')),
                ('precision', models.PositiveSmallIntegerField(default=0, help_text='0 for countable units, 3 for weight.', verbose_name='decimal places')),
                ('step', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Increment used by quantity controls, e.g. 0.1 kg.', max_digits=10, verbose_name='quantity step')),
            ],
            options={
                'verbose_name': 'unit of measure',
                'verbose_name_plural': 'units of measure',
                'ordering': ['name'],
            },
        ),
    ]
