# Generated by Django 5.2.17 on 2026-09-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_pg_trgm_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Shown under the photo in the gallery. Describes this shot — "rótulo", "porção servida" — rather than repeating the product name.', max_length=160, verbose_name='caption'),
        ),
    ]
