# Generated by Django 5.2.17 on 2026-08-09 22:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('key', models.CharField(max_length=255, verbose_name='key')),
                ('scope', models.CharField(max_length=64, verbose_name='scope')),
                ('tenant_id_value', models.UUIDField(blank=True, null=True, verbose_name='tenant')),
                ('user_id_value', models.UUIDField(blank=True, null=True, verbose_name='user')),
                ('request_hash', models.CharField(max_length=64, verbose_name='request hash')),
                ('response_status', models.PositiveSmallIntegerField(default=200, verbose_name='response status')),
                ('response_body', models.JSONField(blank=True, default=dict, verbose_name='response body')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
            ],
            options={
                'verbose_name': 'idempotency record',
                'verbose_name_plural': 'idempotency records',
                'constraints': [models.UniqueConstraint(fields=('scope', 'key', 'tenant_id_value'), name='uniq_idempotency_scope_key_tenant')],
            },
        ),
    ]
