# Generated by Django 5.2.17 on 2026-08-09 22:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('template_key', models.CharField(db_index=True, max_length=64, verbose_name='template')),
                ('recipient', models.EmailField(max_length=254, verbose_name='recipient')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='QUEUED', max_length=12, verbose_name='status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('last_error', models.CharField(blank=True, max_length=500, verbose_name='last error')),
                ('provider_message_id', models.CharField(blank=True, max_length=255, verbose_name='provider message id')),
                ('related_type', models.CharField(blank=True, max_length=32, verbose_name='related type')),
                ('related_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='related id')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Prevents sending the same notification twice.', max_length=128, verbose_name='idempotency key')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email log',
                'verbose_name_plural': 'email logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='notificatio_tenant__a705d1_idx'), models.Index(fields=['related_type', 'related_id'], name='notificatio_related_29b23d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uniq_email_idempotency_key')],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('key', models.CharField(help_text='Stable identifier used by the code, e.g. order.payment_confirmed.', max_length=64, verbose_name='key')),
                ('locale', models.CharField(default='pt-BR', max_length=10, verbose_name='locale')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('html_body', models.TextField(verbose_name='HTML body')),
                ('text_body', models.TextField(blank=True, help_text='Fallback for clients that do not render HTML.', verbose_name='plain text body')),
                ('available_variables', models.JSONField(blank=True, default=list, help_text='Documents which placeholders this template accepts.', verbose_name='available variables')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
                'ordering': ['key', 'locale'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key', 'locale'), name='uniq_email_template_tenant_key_locale')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('PUSH', 'Push notification'), ('SMS', 'SMS'), ('IN_APP', 'In-app')], default='IN_APP', max_length=12, verbose_name='channel')),
                ('notification_type', models.CharField(db_index=True, max_length=48, verbose_name='type')),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('body', models.CharField(blank=True, max_length=500, verbose_name='body')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Deep-link data, e.g. the order the notification refers to.', verbose_name='payload')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('READ', 'Read')], default='QUEUED', max_length=10, verbose_name='status')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx')],
            },
        ),
    ]
